# Generated by Django 5.2.11 on 2026-02-06 07:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="日记标题最多100个字符",
                        max_length=100,
                        verbose_name="标题",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="日记内容最多10000个字符，支持Markdown",
                        max_length=10000,
                        verbose_name="内容",
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("happy", "开心"),
                            ("sad", "伤心"),
                            ("excited", "兴奋"),
                            ("calm", "平静"),
                            ("angry", "生气"),
                            ("tired", "疲惫"),
                            ("loved", "被爱"),
                            ("grateful", "感恩"),
                        ],
                        default="happy",
                        max_length=20,
                        verbose_name="心情",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="日记分类最多20个字符",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="日期",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "日记",
                "verbose_name_plural": "日记",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="相册名称最多50个字符",
                        max_length=50,
                        verbose_name="相册名称",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="相册描述最多200个字符",
                        max_length=200,
                        verbose_name="描述",
                    ),
                ),
                (
                    "cover_photo",
                    models.CharField(
                        blank=True,
                        help_text="封面照片URL",
                        max_length=500,
                        verbose_name="封面照片",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="默认相册，只能有一个",
                        verbose_name="是否默认",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "相册",
                "verbose_name_plural": "相册",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_default"], name="lovezs_albu_is_defa_dfcaf1_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Countdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="重要日标题最多50个字符",
                        max_length=50,
                        verbose_name="标题",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述最多200个字符",
                        max_length=200,
                        verbose_name="描述",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(help_text="重要日日期", verbose_name="目标日期"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("anniversary", "纪念日"),
                            ("birthday", "生日"),
                            ("event", "事件"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("countup", "累计"), ("countdown", "倒计时")],
                        default="countup",
                        help_text="countup: 已过去天数, countdown: 倒计时",
                        max_length=20,
                        verbose_name="方向",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="是否重复"),
                ),
                (
                    "recurring_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yearly", "每年"),
                            ("monthly", "每月"),
                            ("daily", "每天"),
                        ],
                        help_text="每年/每月/每天重复",
                        max_length=20,
                        verbose_name="重复类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "重要日",
                "verbose_name_plural": "重要日",
                "ordering": ["target_date"],
                "indexes": [
                    models.Index(
                        fields=["target_date"], name="lovezs_coun_target__934332_idx"
                    ),
                    models.Index(fields=["type"], name="lovezs_coun_type_6cb024_idx"),
                    models.Index(
                        fields=["direction"], name="lovezs_coun_directi_a4a7b2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                ("path", models.CharField(max_length=500, verbose_name="文件路径")),
                ("url", models.CharField(max_length=500, verbose_name="访问URL")),
                ("size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                ("mimetype", models.CharField(max_length=100, verbose_name="MIME类型")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                (
                    "location",
                    models.JSONField(
                        blank=True,
                        help_text='格式: {"latitude": 数字, "longitude": 数字, "address": "字符串"}',
                        null=True,
                        verbose_name="位置信息",
                    ),
                ),
                (
                    "exif",
                    models.JSONField(
                        blank=True,
                        help_text='格式: {"camera": "相机", "lens": "镜头", "aperture": "光圈", ...}',
                        null=True,
                        verbose_name="EXIF信息",
                    ),
                ),
                (
                    "compressed_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="压缩图URL"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="lovezs.album",
                        verbose_name="所属相册",
                    ),
                ),
            ],
            options={
                "verbose_name": "照片",
                "verbose_name_plural": "照片",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiaryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attached_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="关联时间"),
                ),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lovezs.diary"
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lovezs.photo"
                    ),
                ),
            ],
            options={
                "verbose_name": "日记照片关联",
                "verbose_name_plural": "日记照片关联",
            },
        ),
        migrations.AddField(
            model_name="diary",
            name="attached_photos",
            field=models.ManyToManyField(
                blank=True,
                related_name="diaries",
                through="lovezs.DiaryPhoto",
                to="lovezs.photo",
                verbose_name="关联照片",
            ),
        ),
        migrations.CreateModel(
            name="DiaryTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20, verbose_name="标签")),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_tags",
                        to="lovezs.diary",
                    ),
                ),
            ],
            options={
                "verbose_name": "日记标签",
                "verbose_name_plural": "日记标签",
                "indexes": [
                    models.Index(
                        fields=["diary"], name="lovezs_diar_diary_i_4d71cc_idx"
                    ),
                    models.Index(fields=["tag"], name="lovezs_diar_tag_a3e87f_idx"),
                ],
                "unique_together": {("diary", "tag")},
            },
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["album", "-created_at"], name="lovezs_phot_album_i_17a259_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diaryphoto",
            index=models.Index(fields=["diary"], name="lovezs_diar_diary_i_7867f9_idx"),
        ),
        migrations.AddIndex(
            model_name="diaryphoto",
            index=models.Index(fields=["photo"], name="lovezs_diar_photo_i_e6c4c0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="diaryphoto",
            unique_together={("diary", "photo")},
        ),
        migrations.AddIndex(
            model_name="diary",
            index=models.Index(fields=["-date"], name="lovezs_diar_date_bce157_idx"),
        ),
        migrations.AddIndex(
            model_name="diary",
            index=models.Index(
                fields=["category"], name="lovezs_diar_categor_4442b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diary",
            index=models.Index(fields=["mood"], name="lovezs_diar_mood_eb77eb_idx"),
        ),
    ]
