# Generated by Django 5.2.11 on 2026-02-08 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovezs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="countdown",
            name="recurring_day",
            field=models.IntegerField(
                blank=True,
                help_text="每年重复时的日期 (1-31)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="重复日期",
            ),
        ),
        migrations.AddField(
            model_name="countdown",
            name="recurring_month",
            field=models.IntegerField(
                blank=True,
                help_text="每年重复时的月份 (1-12)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="重复月份",
            ),
        ),
    ]
