# Generated by Django 5.2.11 on 2026-02-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovezs", "0005_alter_diary_options_diarycomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="是否公开"),
        ),
    ]
