# Generated by Django 5.2.11 on 2026-02-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovezs", "0006_diary_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="日记内容最多10000个字符，支持Markdown",
                max_length=10000,
                verbose_name="内容",
            ),
        ),
    ]
