# Generated by Django 5.2.11 on 2026-02-16 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovezs", "0007_allow_blank_diary_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="diarycomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="lovezs.diarycomment",
                verbose_name="父评论",
            ),
        ),
    ]
