# Generated by Django 5.2.11 on 2026-02-18 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovezs", "0009_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diary",
            options={
                "ordering": ["-is_pinned", "-created_at"],
                "verbose_name": "日记",
                "verbose_name_plural": "日记",
            },
        ),
        migrations.AddField(
            model_name="diary",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="是否置顶"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("diary_comment", "日记评论"),
                    ("diary_created", "新日记发布"),
                    ("diary_like", "日记点赞"),
                ],
                max_length=20,
                verbose_name="通知类型",
            ),
        ),
        migrations.AddIndex(
            model_name="diary",
            index=models.Index(
                fields=["-is_pinned", "-created_at"],
                name="lovezs_diar_is_pinn_53e750_idx",
            ),
        ),
    ]
